#!/usr/bin/env bash

##
# Usage
#
# Updates current branch based on its name:
# $ git update
#
# Updates with rebase rather than merge
# $ git update rebase
#
#
# Updates with rebase from a specified origin
# $ git update rebase upstream
##
# exit on error
set -e

git fetch > /dev/null 2>&1
source develop-exists.sh
source default-branch.sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
TYPE=$1
REMOTE=${2:-origin}

if [[ $BRANCH = "$MAIN" ]]; then
  echo "you can't update $MAIN silly"
  exit 255
fi

git fetch  # get new stuff

if [[ ${BRANCH:0:8} = "feature/" || $DEVELOP_EXISTS -eq 1 ]]; then
 if [[ $TYPE = 'rebase' ]]; then
    git rebase "$REMOTE/develop"
  else
    git merge "$REMOTE/develop"
  fi
else
  if [[ $TYPE = 'rebase' ]]; then
    git rebase "$REMOTE/$MAIN"
  else
    git merge "$REMOTE/$MAIN"
  fi
fi

