#!/usr/bin/env sh

##
# Usage
#
# Start a hotfix/1234 branch (off main by default)
# $ git start hotfix 1234
#
# Start a feature/1234 branch (off develop by default)
# $ git start feature 1234
#
# Start a whatever/1234 branch off main as specified
# $ git start whatever 1234 main
#
# Start a "whitebox" branch(off develop by default)
# git start wb 1234-TestBranch
##

# exit on error
set -e
source default-branch.sh

if [[ $1 = '' || $2 = '' ]]; then
  echo "Please specify a type (e.g. hotfix) and name (e.g. 1234)"
  exit 255
fi

[[ $1 = 'hotfix' ]] && BRANCH=$MAIN || BRANCH='develop'
[[ $3 != '' ]] && BRANCH=$3

git checkout $BRANCH
git pull origin $BRANCH


# checking for a hyphen, otherwise use the default branch prefix name
#[[ $2 =~ .*-[0-9]+$ ]] && BRANCH_NAME=$2 || BRANCH_NAME="$JIRA_PROJECT-$2"
BRANCH_NAME=$2
if [[ $1 = 'wb' ]]; then
  git checkout -b $BRANCH_NAME
else
  git checkout -b $1/$BRANCH_NAME
fi
